### ISSUE TITLE
Crash w/ Ranch Spawn-1.10.2

### ISSUE THREAD

**Issue by WenXin20** [Brian-Wuest/MC-Prefab#10]
Forge 2076
I crashed when generating the ranch using white glass facing west. I had received a NPE after using the preview, and then got a crash when spawning in the ranch.
[Crash Report](http://pastebin.com/T5JBiwW0)

**Comment by Brian-Wuest** [comment]
I think I know what happened here. When the mine shaft is being placed it gathers up all of the resources as it's breaking the blocks and puts them into the chest at the bottom of the mine shaft. Because of the number of different types of blocks which were accumulated when you built the house, there wasn't enough room in the chest and the run-time error occurred.

I will update this process to to place a second chest if there are too many blocks to place. If there are too many for a double chest, the extras will just have to be lost.

**Comment by WenXin20** [comment]
Ok, thanks, I checked the chest and it was full.

**Comment by Brian-Wuest** [comment]
This has been addressed with version 1.1.1.1 which has just been released.

**Comment by WenXin20** [comment]
Thanks
