### ISSUE TITLE
[1.14.4] Unable to place structures on a server- Error executing task on Server java.lang.IndexOutOfBoundsException:

### ISSUE THREAD

**Issue by ProsperCraft** [Brian-Wuest/MC-Prefab#104]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.14.4
    1. Forge Version: forge-1.14.4-28.0.46
    1. Mod Version: prefab-1.4.0.1
1. What type of issue is this? Choose one of the following:
    1. **Bug** (Something doesn't work the way you expect or the game crashes/has an issue)

Modpack - https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

This may be a conflict with Slurpees dongles.

Stacktrace-
https://gist.github.com/ProsperCraft/dd10acd6ac5e30c7c968b518838d4456

[latest.log](https://github.com/Brian-Wuest/MC-Prefab/files/3506858/latest.log)
[debug.log](https://github.com/Brian-Wuest/MC-Prefab/files/3506859/debug.log)

**Comment by Brian-Wuest** [comment]
This is a defect on their side. What the BreakEvent and PlaceEvent are supposed to do is double check that those events can be done for the specified block because some mods make their blocks unbreakable through these events. 

A lot of mods which create mazes or dungeons do this so players cannot just dig themselves out of the dungeon in order to get to the loot by using a Diamond/Obsidian pickaxe.

Since this a defect in their code and I am passing everything I need to to the event, I am going to close this issue.

**Comment by ProsperCraft** [comment]
Resolved on Slurpies dongles side.

**Comment by ProsperCraft** [comment]
1.4.0.1 works on servers :)
