### ISSUE TITLE
[1.14.4] Server crash - NoSuchMethodError: net.minecraft.entity.player.PlayerInventory.func_184429_b(Lnet/minecraft/item/ItemStack

### ISSUE THREAD

**Issue by ProsperCraft** [Brian-Wuest/MC-Prefab#105]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.14.4
    1. Forge Version: forge-1.14.4-28.0.49
    1. Mod Version: prefab-1.4.0.1
1. What type of issue is this? Choose one of the following:
    1. **Bug** (Something doesn't work the way you expect or the game crashes/has an issue)
Crash log-
   https://gist.github.com/ProsperCraft/ef005f4eeb74002d5134e1103592997a

Crash was caused by using the village house blacksmith option on prefab on a dedicated server.

**Comment by Shadows-of-Fire** [comment]
Invocation of client-only method `InventoryPlayer#getSlotFor` on this line https://github.com/Brian-Wuest/MC-Prefab/blob/master/src/main/java/com/wuest/prefab/Structures/Config/StructureConfiguration.java#L192

**Comment by Brian-Wuest** [comment]
Razelfrazen......I need to clean up my code.

Really sorry about that :(

I will get a fix out soon, I want to generate the other buildings on a server to make sure I didn't miss anything.

**Comment by Brian-Wuest** [comment]
The worst part was that the method call wasn't even necessary!

**Comment by Brian-Wuest** [comment]
This has been fixed with 1.4.0.3 which has been uploaded to CurseForge and will be available once it's approved.

In addition, the Aqua Base was fixed to address an issue with running water at the entrance.

And the Structure Part item was updated to address an issue on the GUI where the Style button didn't exist.

Closing this issue.

Thank you!
