### ISSUE TITLE
Adding new structures with datapacks?

### ISSUE THREAD

**Issue by Syndaryl** [Brian-Wuest/MC-Prefab#106]
Hi, I've been snooping around in your codebase and it looks like the structures are implemented with the minecraft structure system (yay! a standard!)

Is it possible to add a new structure with a datapack/resourcepack? Or does it require a code change for total support?

I would like to add some biome-specific villager-houses items to be able to better integrate into various biomes, and I'd also like to add some structures that rely on Biomes-o-plenty blocks.

**Comment by Brian-Wuest** [comment]
haha! I caught you! You fell into my trap!

In all seriousness, I actually do not use the Minecraft Structure System. It may look similar but I wrote it myself. 

While it is a pain to maintain it does support structures larger than a chunk. The moderate houses are actually 4 chunks in size. 

At this time there are not plans for allowing custom structures mostly due to this custom buildings. If I were to allow custom buildings I would probably use the existing system just so I don't have to worry about it.

Unfortunately, that's a long ways off as I want to update my other mods to 1.14 and maintain this one.

**Comment by Brian-Wuest** [comment]
I am closing this for now.
