### ISSUE TITLE
Subaquatic Style house bit annoying to enter.

### ISSUE THREAD

**Issue by STOKE-STER** [Brian-Wuest/MC-Prefab#123]
What version of Minecraft, Forge and Mod are you running?
    Minecraft Version:1.15.2
    Forge Version:forge-31.1.0
    Mod Version:prefab-1.5.0.0.jar
What type of issue is this?
     **Bug** (Something doesn't work the way you expect or the game crashes/has an issue)
     Details: The new underwater starter house has a block gap between the main floor and the water you swim up under.
![2020-02-06_23 05 34](https://user-images.githubusercontent.com/36657224/73939817-fa521880-4935-11ea-869f-1743e2b2d145.png)

Not a massive problem but it makes getting into and out of the house a bit annoying at first. Could you possibly raise the water level in this area by one to make getting in and out easier?

**Comment by Brian-Wuest** [comment]
Well that's embarrassing!

I really can't increase the water there (I don't include the water in the build configuration file) but what I did is make the ledge there have stairs instead of full blocks so you can get up into the house properly.

Screen shot seen below.

![2020-02-06_18 02 13](https://user-images.githubusercontent.com/13502068/73989269-dfb67a00-490a-11ea-8d54-bef288ab7d14.png)

**Comment by STOKE-STER** [comment]
Awesome fix :) Looking forward to seeing it in an update :)

**Comment by Brian-Wuest** [comment]
This has been updated with version 1.4.0.10 and 1.5.0.1. Currently waiting on approval for 1.4.0.10 from curseforge before uploading the next one. Closing this issue.
