### ISSUE TITLE
[1.15.2] Client crash when placing a house. java.lang.NoClassDefFoundError: javafx/util/Pair     at com.wuest.prefab.Structures.Gui.GuiStartHouseChooser.

### ISSUE THREAD

**Issue by ProsperCraft** [Brian-Wuest/MC-Prefab#125]
https://github.com/ProsperCraft/towncraft/issues/40

Please see linked issue for logs.

1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.15.2

1. What type of issue is this? Choose one of the following:
    1. **Bug** (Something doesn't work the way you expect or the game crashes/has an issue)

1. If this is a **bug**, please provide as much detail as possible for the issue that you are running into. If possible post a log file to PasteBin or another similar site.

**Comment by Brian-Wuest** [comment]
This is due to using OpenJDK which I am not supporting. Minecraft is created using the official JDK from Oracle and thus could break _at any time_ if you use OpenJDK.

Could I fix this one issue; sure. But that opens the floodgates for everything that can be different between Oracle's JDK and OpenJDK and I don't need that noise. Especially as they become more and more divergent. I.E. OpenJDK updates functionality in base methods that exists in both OpenJDK and Oracle JDK and now I have differing functionality as a result. No thank you.

If Minecraft or Forge ever go the route of embracing OpenJDK I will fix this and FULLY embrace OpenJDK. However; until that time this will not be fixed.

https://gist.github.com/androidfred/bc64da9e6a355b984d37439ed63ae16b

**Comment by ProsperCraft** [comment]
Fortunately, this is a client crash because all of our dedicated servers have been running openJDK for a  decade now.
