### ISSUE TITLE
Preview Doesn't Render

### ISSUE THREAD

**Issue by WenXin20** [Brian-Wuest/MC-Prefab#134]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: v1.15.2
    1. Forge Version: v31.1.35
    1. Prefab Version: v1.5.0.3
    1. OptiFine: vHD U G1 Pre13
    1. OptiForge: v0.1.7
1. What type of issue is this? Choose one of the following:
    1. **Bug**
1. Prefab is not rendering the preview of the structure on my server.
 - I suspect it's because OptiFine and OptiForge is installed. [OptiForge](https://www.curseforge.com/minecraft/mc-mods/optiforge)  is used so that OptiFine will work with Forge. It also requires [MixinBootstrap](https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap).
 - A similar issue was reported for Structurize at ldtteam/Structurize#112.

**Comment by Brian-Wuest** [comment]
Optifine interferes with the shader processing at a fundamental level. Botania doesn't support Optifine with it's own preview features. Since the Structure Preview was based on Botania's preview function I cannot support it either.

Closing issue.

**Comment by WenXin20** [comment]
I don't have any shaders enabled, this happens with the default. And, from what I remember, it was compatible with Optifine in 1.12. 
Does the no shaders make a difference?

**Comment by Brian-Wuest** [comment]
I don't think so. I have never used Optifine since there have been tons of issues with it and Forge not being compatible with each other. I also honestly don't know too well how the preview works since I don't really do graphical engineering. I was able to tinker around a bunch with what Botania had to get it to work. 

So basically unless Botania can get it to work; I simply won't be able too. Sorry.

**Comment by WenXin20** [comment]
Hmm, maybe the author of OptiForged can help?
He made a similar issue at ldtteam/Structurize#112.
But if not, I can do without.
