### ISSUE TITLE
Enhancemen idea for 1.15

### ISSUE THREAD

**Issue by IchigoGames** [Brian-Wuest/MC-Prefab#136]
Enhancement ideas

i like this mod but had to remove it due to player spawning in buildings at spawn i would like to see two thinks added-changed

1. a check for spawn protection if found would be unable to place down
2 .a config option to turn off starting with home blueprint i believe this was in past versions but i am unable to to find it in 1.15 so i would like that re added.

**Comment by Brian-Wuest** [comment]
What are you doing to add spawn protection? Is it a mod or an option you chose when starting your world (it's been a long time don't remember!).

For the second one, there is already an option to not give the starter house.
Below is the name of it and what you can set it to in order to not give a starter item.
"Starting Item" = ""

Also; screenshot!
![image](https://user-images.githubusercontent.com/13502068/79055541-8113c200-7c13-11ea-9c00-69a2009a6271.png)

**Comment by IchigoGames** [comment]
nope tested in in singeplayer and on server with both server and client configs changed to pic above and it will still spawn you with a house but i suppose now i need to put in a issue ticket

**Comment by Brian-Wuest** [comment]
Yes please; let's track that separately. I will test it out later tonight.

**Comment by IchigoGames** [comment]
i was talking about normal Vanilla minecraft spawn protection

**Comment by Brian-Wuest** [comment]
This was fixed with version 1.4.0.13 and 1.5.0.4

Closing issue
