### ISSUE TITLE
Preview Crash 1.10.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Brian-Wuest/MC-Prefab#16]
Crash log Client
https://gist.github.com/P3rf3ctXZer0/8388ac073384c73b24383eb12715ef13

Full Log Client
https://gist.github.com/P3rf3ctXZer0/348661140d32f88659cdaf8306dbdfc4

So yeah my modpack is kind of huge. I hope that you can help fix it. Since it crashed when I previewed my ranch house.

**Comment by Brian-Wuest** [comment]
This issue is due to ArchitectureCraft. That mod is registering a base renderer for vanilla minecraft objects (like a chest in this case). This has been reported a few times but ArchitectureCraft hasn't addressed this yet.

I will see if there is something I can do since this only seems to be a problem with Chests. If I cannot I will have to disable the preview feature when the offending mod is present, sorry ☹️.

**Comment by P3rf3ctXZer0** [comment]
Oh no thank you so much! I am so grateful you took the time to diagnose the issue. I know its not always easy for mods to play nice when like 233 mods are present. So thank you sincerely for taking your time to explain the situation to me.

**Comment by Brian-Wuest** [comment]
So I feel like a real dummy on this particular issue. After much debugging I was able to pinpoint the mod which was actually causing the issue (which wasn't ArchitectureCraft like I thought it was). This was actually an issue coming MalisisDoors which adds animation to the vanilla doors.

I have pushed an update to CurseForge and it should be approved in a few minutes. It will be version 1.1.1.5.

Closing this issue.
