### ISSUE TITLE
In multiplayer, the mod destroys the privates of other players

### ISSUE THREAD

**Issue by masterrip** [Brian-Wuest/MC-Prefab#20]
This is a very good mod! Thank You!
Sorry! My English is very bad =)
In multiplayer, the mod destroys the privates of other players. And destroying buildings the server.
Please add support for sponge plugins:
https://forums.spongepowered.org/t/shield-anti-grief-redprotect-1-8-9-1-11/11846
https://forums.spongepowered.org/t/griefprevention-official-thread-1-8-9-1-10-2-1-11/1123

**Comment by Brian-Wuest** [comment]
This is a forge-only mod. I don't use Sponge and I don't expect my mod to work properly with it. There is already an anti-griefing process within the mod but uses the Forge Event bus for it. However, it is reliant upon other mods to implement this protection. I can write up a wiki page for it so that other users know what is expected.

**Comment by masterrip** [comment]
Thank you for your attention to my problem. I ask you to give me advice. How to solve this problem. Thank you =)

**Comment by masterrip** [comment]
Your mod is the best start kit for any server.
If the event was tied to the unit installation may anti griffing plug-ins could deny.

**Comment by Brian-Wuest** [comment]
I have written up a wiki page for how other modders can implement the anti-griefing processes implemented in this mod.

You can find it here: https://github.com/Brian-Wuest/MC-Prefab/wiki/Anti-Griefing

Since you have forge on your server you might look into some standard forge block/area protection mods available for forge. I think "FTBUtilities" (which requires FTBLib) has something like this.

**Comment by masterrip** [comment]
The idea is there. The influence of fashion , you can limit if it is tied to the unit. 
Mod can not limit, but you can limit the installation of the unit. Only allowed in the region owned by the player. In private.
Something like this:
http://preciousstones.shoutwiki.com/wiki/Main_Page

**Comment by masterrip** [comment]
Thank You! You very helpful people :)

**Comment by Brian-Wuest** [comment]
That's a pretty cool mod and I like where it is going but that is also a non-forge mod, It's bukkit.

**Comment by masterrip** [comment]
I understand it. = )

**Comment by Brian-Wuest** [comment]
Here is the link to FTB Utilities.

It has a "Chunk Claiming" feature. This allows players to claim an area so only the player and their friends can build in that chunk. This uses the events I am utilizing for my Anti-Griefing process.

https://minecraft.curseforge.com/projects/ftb-utilities?gameCategorySlug=mc-mods&projectID=237102

I will be closing this issue.
