### ISSUE TITLE
[Bug]: Abuse Bug from Modern House + Instant Bridge

### ISSUE THREAD

**Issue by itsdinkd** [Brian-Wuest/MC-Prefab#245]
### Minecraft Version

1.17

### Mod Version

Latest Fabric Version

### Details

The items that are durability based can be repaired by Dark Enchanter mod and allow the user to place as many modern houses or instant bridges as they want. This has happened on my server and some troll spammed these buildings everywhere.

**Comment by Brian-Wuest** [comment]
I cannot find a mod with name "Dark Enchanter" so I wouldn't know how to counteract this. There are probably a bunch of other mods which allows this as well.

The recipes are set up to expect the multi-use functionality.

You can always turn the recipes for these buildings off if you have issues with them on your server. They can still be provided via the creative menu because we don't conditionally register items as that causes syncing issues between server and client.

Aside from coming up with our own durability mechanism for our items or adjusting the recipes to only do a single build there isn't anything we can do for this type of issue.

While I can understand that having someone do this in your world, I don't have the time available to come up with a brand-new durability system nor update the recipes. I am a single developer working on this mod with a full-time day job with a family and other hobbies, so time is of short supply.

We have a number of other defects to address as well as updating both Forge and Fabric versions of this mod to 1.18 and whatever issues _that_ comes with.

**Comment by itsdinkd** [comment]
It's more for my modpack, "another quality modpack 2", than my server as I
wouldn't want this to happen in anyone's server. I get what you're saying
though. I also have a full time job with a family with 2 kids and solely
operate and develop 3 modpacks so I know exactly what you mean lol.

The mod is called Dark Enchanting.
