### ISSUE TITLE
[Bug]: Swift blade in Starter Chest while it's disabled

### ISSUE THREAD

**Issue by itsdinkd** [Brian-Wuest/MC-Prefab#281]
### Minecraft Version

1.19.2

### Mod Version

1.9.2.5

### Details

`"Swift Blade": false,` in config

Starting Chest provides a stone swift blade in chest.

**Comment by itsdinkd** [comment]
Player also reported that before we changed the seed it was a regular stone sword, but then when a new world started, it turned into a stone swift blade.... not sure how that worked.

**Comment by Brian-Wuest** [comment]
I have not been able to duplicate the issue with the swift blade being in the chest when the recipe is turned off.

Since this is a server, the configuration setting for that recipe needs to be on the server's configuration as that's the master record for almost every setting.

As for things being weird when you change the seed. That is something not normal (in my opinion), so I am not going to address issues with changing of a world seed between launches.

**Comment by itsdinkd** [comment]
>Since this is a server, the configuration setting for that recipe needs to be on the server's configuration as that's the master record for almost every setting.


yep. the configs are synced between client and server in my pack.
