### ISSUE TITLE
[Enhancement]: Block Non-Vanilla SwiftBlade

### ISSUE THREAD

**Issue by AmyRose1288** [Brian-Wuest/MC-Prefab#284]
### Minecraft Version

1.16.5-1.19.4

### Forge Version

36.2.35-45.0.43

### Mod Version

1.6.5.16-1.9.3.0

### Details

Some SwiftBlade does not have a Vanilla Variant (Or is Requiring Extra Mods),pls add a option to block those or remove them from the pack

For Example:Swift Blade (osmium) Requires “forge:ingots/osmium” which is Currently Only Available Via Installing mekanism

**Comment by Brian-Wuest** [comment]
This mod is no longer under development.

For the swift blades that don't have default ingredients (like the osmium one mentioned) they are only available in creative or if the specific tag was registered. 

The only way to truly remove the item would be to remove it entirely from the mod as all items have to be registered regardless of configuration settings.

This is true for all items and blocks in the mod. So even if you turn off the recipes for the various blueprints, a player with access to the creative menu or command block command can get it. 

This is _by intention_ so that modpacks can provide these items as quest rewards but keep the recipes disabled.
