### ISSUE TITLE
Still missing 1.20.1

### ISSUE THREAD

**Issue by nul666lun** [Brian-Wuest/MC-Prefab#292]
### Minecraft Version

1.20.1

### Forge Version

huh?

### Mod Version

its missing

### Details

quite simple.. 1.20.1 forge is still missing even tho you closed all the issues with people asking ... 1.20.6 does no good.. where is 1.20.1?

**Comment by Brian-Wuest** [comment]
You have to remember that this is a hobby project. Me and the rest of the team take time out of our weekends and evenings after our day jobs to work on this instead of going out with friends, playing games and\or doing things with family.
 
We do it for the love of the game, the community, the mental challenge of the code (that's my thing at least) or a whole host of other reasons.

But we don't get paid for this passion. As such, we have to draw the line somewhere. For every player that wants version X, there will be one that wants version Y.

I was away from this project for a long time (1.5 years!) and when I came back we talked about it and it only made sense to go after the latest version of Minecraft for 1.20.

What Mojang puts in these "drops" may be small for players, but the effects they have as a modder are quite severe, and I like to take my time to make sure things are right before they go out. Having said, that you will notice that there were issues with how recipes were handled and I had to release some fixes almost immediately? Well that's because Mojang changed things in one of their "drops" and messed up my process.

For the past month(ish) I have spent pretty much every evening and most weekends working on updates or testing things in one way or another with the goal of getting 1.20.6 AND 1.21.1 out with both Fabric and a brand new mod-loader for the project (that being NeoForge). I am ground out as a result.

This unfortunately turned into a gripe session, but the tldr; is that ...no we will not support or backport to 1.20.1. We will only support the latest minor release of a major version of Minecraft we have a release for. In this example, that would be 1.20.6.
