### ISSUE TITLE
[Bug]: softlock when choosing house type

### ISSUE THREAD

**Issue by VaporeonScripts** [Brian-Wuest/MC-Prefab#299]
### Minecraft Version

1.21.1

### Forge Version

latest neoforge

### Mod Version

latest

### Details

https://mclo.gs/BoQmb4p

https://mclo.gs/igVqqgD

**Comment by Brian-Wuest** [comment]
Looks like it's a bunch of other mods causing the issue or your not on the correct version of Java. You need to be on Java 21 and it looks like you may be on 17.

**Comment by VaporeonScripts** [comment]
not rlly possible? wouldnt even turn on with java 17

**Comment by VaporeonScripts** [comment]
it happens with java 21 too, it got reported by many users

**Comment by VaporeonScripts** [comment]
https://mclo.gs/kqa00Dr

**Comment by Brian-Wuest** [comment]
Yeah, there are a few errors going on in that log.

In here, some icon is busted (not prefab). Screenshot taken from phone as I was on a break 
![Screenshot_20250109-141907](https://github.com/user-attachments/assets/539ba4b6-58df-4789-a202-82efe8c763a3)

In here, some JEI plugin failed (not prefab).
![Screenshot_20250109-142228](https://github.com/user-attachments/assets/edd41bf8-b37f-4662-a06d-2ca971217bba)

In here, another JEI recipe viewer, this time Melanism (great mod choice, but still not prefab) caused an error.

![Screenshot_20250109-142407](https://github.com/user-attachments/assets/a6feade0-097c-491a-a374-fc72b10246c6)

In all 3 of these cases the Prefab mod does show up in the list because we do have a rending mixin but then again so do like a dozen other mods.

If you can pinpoint a specific error in this log that I can work with that looks like we caused it, I can get further with this but right now there is too much information that is not showing me a relationship between these errors and Prefab.

**Comment by VaporeonScripts** [comment]
basically when right clicking the house the screen freezes and no logs are sent, also those errors happened even when prefab was working

**Comment by Brian-Wuest** [comment]
This mod works fine insolation so there is some other mod that is messing with the vanilla screen rendering code. We cannot help much with that. Especially if the game refuses to provide a log file.

The best I can suggest is take mods out of a test environment with your modpack until the issue goes away as that's what I would have to do. Given from what I've seen in the log file, you have easily over 100 mods so that's a tall order and I'm sorry that I cannot be much more help but mod compatibility issues creep up from time to time.
