### ISSUE TITLE
1.11 Starting House Bug

### ISSUE THREAD

**Issue by noncivilisedeye** [Brian-Wuest/MC-Prefab#38]
When placing the ranch-style house into a randomly generated survival world, upon completing construction, several game achievements are granted simultaneously.

**Comment by Brian-Wuest** [comment]
This has been a part of the Starting House since the it was a part of WuestUtilities. This way the player doesn't have to go through the basic achievements such as creating a crafting table/furnace since the house provides those.

This was inspired from Wood achievement received when the player gets a log from a starting chest, drops the piece of wood and picks it up to get that associated achievement.

**Comment by noncivilisedeye** [comment]
Aha, my mistake, I looked over the mod info here and on curseforge for an explanation, but as I assumed it was a bug, likely skimmed right past something telling me just that. Thank you for clearing that up, and for the prompt reply.

**Comment by Brian-Wuest** [comment]
No problem, glad I could clear that up!
