### ISSUE TITLE
[Suggestion] Save settings when previewing structures

### ISSUE THREAD

**Issue by BrisingrAerowing** [Brian-Wuest/MC-Prefab#44]
Having to reconfigure a structure each time it is previewed is kind of annoying, and I think it would be useful to save the configured settings.

I noticed that some structures do this, but some (like the Warehouse) don't.

Also, how about a way to undo the generation of a structure? Not required (I can easily World Edit the structure away), but would be useful.

**Comment by Brian-Wuest** [comment]
Yeah, I should be consistent with the settings with all of the structures.

Marking this as a bug since this is not consistent.

I don't think I can un-do the structure generation once it's built since I don't know if the player put anything there to begin with.

**Comment by BrisingrAerowing** [comment]
OK, fair enough on the undo part.

**Comment by Brian-Wuest** [comment]
As a head's up, with how I did this. The settings will be saved if you preview or cancel.

The settings will also be saved between items. So if you build 1 starting house and then get another (because I'm adding a way to craft it), the settings you used from the first time will be used again.

Caveat: Once you leave a single player game or change multi-player servers the settings are lost.

**Comment by Brian-Wuest** [comment]
Released in versions 1.1.1.15 for MC 1.10.2 and 1.2.0.10 for MC 1.11.2.
