### ISSUE TITLE
[Suggestion] item naming

### ISSUE THREAD

**Issue by Andvee** [Brian-Wuest/MC-Prefab#69]
In the version of Prefab I'm running many of the prefab spawning items get the name `prefab:item_basic_structure` with no NBT tags or metadata to distinguish them. This discourages usage in modpacks because CraftTweaker and Better Questing cannot handle these items properly, and defaults to the Advanced Chicken Coop.

**Comment by Brian-Wuest** [comment]
Make sure you have updated to the latest version. I fixed a number of issues with that in 1.11.2 and 1.12.2.

If you are providing these items as quest rewards, they need to have the nbt tags or they don't work. I use as mid specific forge capability to distinguish the different items.

**Comment by Andvee** [comment]
Okay wasn't aware if that had changed in newer versions or not. The pack I'm working on is stuck in 1.10.2 until one of the primary mods it's balanced around updates. Issue is resolved in future versions then thanks.

**Comment by Brian-Wuest** [comment]
No problem. What I can do is update the WIKI for modpack devs to include the capability information so they can have the NBT data for these rewards system mods.

**Comment by Brian-Wuest** [comment]
Finally got around to this. I provided documentation for mod-pack developers on what the NBT data needs to be when rewarding certain items.

Since you are using 1.10.2 certain blueprints won't show up in your version. They were only added for 1.11.2 and above.

If you think that there needs to be more information added please re-open this issue and let me know!

Here's the link to the page.
https://github.com/Brian-Wuest/MC-Prefab/wiki/Blueprint-NBT
