### ISSUE TITLE
enhancement - Include air blocks in the bridge to clear tunnels.

### ISSUE THREAD

**Issue by ProsperCraft** [Brian-Wuest/MC-Prefab#76]
Currently when you place a bridge the blueprint doesn't include air blocks over the bridge, so you have to painstakingly dig it out when going through a mountain, would you please edit the blueprint to include air blocks to clear the ground in the tunnel?

![2018-01-31_12 12 50](https://user-images.githubusercontent.com/4427684/35642450-63a22f78-0680-11e8-9b94-e01d54c5e10b.png)

**Comment by ProsperCraft** [comment]
This walkway was cleared down the middle by hand.

**Comment by Brian-Wuest** [comment]
I think that sounds reasonable.
I woujld do this for 1.11.2 and 1.12.2, does that sound okay?

**Comment by ProsperCraft** [comment]
I only need 1.12.2 so yes :)

**Comment by IamAlathe** [comment]
@ProsperCraft It's a bridge, I never would have thought to use it as a tunnel.  You're a genius.  I like this idea.

I wouldn't mind seeing some bridge upgrades such as being able to change the length, or maybe a nicer block option, stone brick or wood planks or something.  Just thoughts.

**Comment by Brian-Wuest** [comment]
Sorry, had a Muslim. Didn't mean to close the issue!

**Comment by Brian-Wuest** [comment]
Maybe make it like the other structures where it has a normal Gui?

**Comment by Brian-Wuest** [comment]
Here are my thoughts for the gui.
We can have a button which cycles through different material types available. I am thinking all of the different types of wood, cobble stone, stone and variants and stone bricks. 

There would be another option for the length of the structure. I am thinking 25 to 75 blocks in total. 

The preview function will be interesting to address since it doesn't really handle variable structure sizes (hence the basic house doesn't have it).


The total material options would be:
1. Oak
1. Dark Oak
1. Birch
1. Jungle
1. Spruce
1. Acacia
1. Cobblestone
1. Stone
1. Granite
1. Diorite
1. Andesite
1. Stonebrick

**Comment by ProsperCraft** [comment]
annnnddd. Chisel? :)

Also I LOVE the idea of a variable length!!

How about an intersection prefab too?

**Comment by Brian-Wuest** [comment]
I could do chisel as well. An intersection you could do manually, just need to clear the walls it creates :smile:.

**Comment by Brian-Wuest** [comment]
I have some screen shots of what the instant bridge will look like. I added a roof. With this being used for a tunnel, what good does that do if lava starts pouring down you because you generated this in the nether?

There is an option to not have a roof so it can be an open topped bridge.

Thoughts? Comments?

![2018-02-07_18 18 03](https://user-images.githubusercontent.com/13502068/35969312-11ae5b8a-0c8c-11e8-9fbe-bf316eed4bce.png)

![2018-02-07_18 18 31](https://user-images.githubusercontent.com/13502068/35969317-146aae82-0c8c-11e8-8dd5-3a134f5f17ce.png)

![2018-02-07_18 18 38](https://user-images.githubusercontent.com/13502068/35969319-19228fbc-0c8c-11e8-9723-7ca39167d81f.png)

**Comment by litjohn50** [comment]
If you can include a height option for us. We are going to be using another mod for a train. and would love to run these through them.

**Comment by Brian-Wuest** [comment]
Default to the 3 block interior hight with a max of 8?

**Comment by litjohn50** [comment]
that sounds good

**Comment by Brian-Wuest** [comment]
Here's what I've got for the updated GUI.

![2018-02-09_06 20 40](https://user-images.githubusercontent.com/13502068/36027564-75a3f20a-0d61-11e8-90e7-3bae16a97f22.png)

**Comment by Brian-Wuest** [comment]
Here is what a full-height tunnel (with roof) looks like.

![2018-02-09_06 45 56](https://user-images.githubusercontent.com/13502068/36028534-fd93f036-0d64-11e8-99f9-fd4609cedf0a.png)

**Comment by Brian-Wuest** [comment]
One thing that I haven't mentioned yet and I don't know is very clear from the images is that the bridge will no longer be able to be generated by right-clicking on liquids or on air blocks. It will spawn like other structures where you have to right-click on the top of a solid block to show the preview or to build it.

This means that if you are doing a Sky Bridge type of thing, you need to start with a 1 block wide tower and then go from there.

I changed this aspect because the placement of the middle walkway block was usually off to the left because when placing blocks this way I have to rely on the player's position instead of a hard block position. This change makes the middle walkway block where you expect it to be consistently.

Unless there are further suggestions or issues I will be releasing this change on Monday.

**Comment by Brian-Wuest** [comment]
This has been released with 1.2.0.19 (MC 1.11.2) and 1.3.0.16 (MC 1.12.2).

Thank you for all the feedback.

**Comment by ProsperCraft** [comment]
Updated thank you.

**Comment by IamAlathe** [comment]
I forget to check in here for a couple of weeks, and you've gone and done all the things!  This is awesome!  Thank you so much!
