### ISSUE TITLE
Not a bug just a suggestion

### ISSUE THREAD

**Issue by mackie419** [Brian-Wuest/MC-Prefab#77]
I was trying to find somewhere to leave you a comment with some suggestions but have not found anything to say where to leave this for you. 

Was wondering if it would be possible to look at making some theme style builds ie: western style theme, or any other themes out there.

If there is a place to leave you comments could you leave it here.

Thank you and great work on the mod. I really love this mod.

**Comment by Brian-Wuest** [comment]
I like the idea of themed buildings. We haven't had many ideas for new buildings recently (I.E. months). I will shoot this by Kaojinn and see what he thinks.

Thanks!

**Comment by mackie419** [comment]
Thats kewl thank you for the response. I making a pack that i want to do like a western theme around that includes trains and all. So maybe an idea could be like a train station or something. Since i lack the creativity for building stuff I thought I would throw the idea out there. But again great work you guys are doing, keep up the good work.

**Comment by SunSeek** [comment]
Also wanted to make a suggestion. How about including parts of a building for modular design?
Things like 5*5 wall parts, gates, towers, 5*5 frames in various materials, even 7*7's and 9*9's.  This is perfect to take on that modular design structure rather than just total complete builds.

Could even do the modular design in various styles: medieval, modern, Minecraft noob, desert, Western as was previously mentioned, 

Also wanted to mention map art. Just the idea alone that you could have duplicatable map art blows my mind. I know it's a tricky subject mostly dealing with copyright issues but surely there are some map artists that would love to have their original art out there for everyone to see.

**Comment by Brian-Wuest** [comment]
Not sure how we hadn't thought of something like this already. I love the idea of Prefab "Parts"!

**Comment by Brian-Wuest** [comment]
@SunSeek I am moving your suggestion for minecraft parts to their own issue. I will track a "western" style saloon and maybe jail with this issue.

Sorry that this has taken so long, life has been busy.

**Comment by Brian-Wuest** [comment]
@mackie419 - I have added the Jail with 1.3.0.24 which is now available on CurseForge. It's more of a modern jail than a "Western" style. As far as the saloon, we can try creating something that will come close but the aesthetics of minecraft might make that difficult.

**Comment by Brian-Wuest** [comment]
The saloon has been added in 1.3.0.26. 

Closing this issue.
