### ISSUE TITLE
Furnaces in starter houses

### ISSUE THREAD

**Issue by Davoleo** [Brian-Wuest/MC-Prefab#82]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.12.2
    1. Forge Version: 2673
    1. Mod Version: 1.3.0.19

    1. **Bug** (Something doesn't work the way you expect or the game crashes/has an issue):
I disabled the vanilla furnace in starter houses, you can't find it in the default one but you can in other kind of starter houses such as Ranch style, Hobbit style, Snowy style, Desert style...

Screenshots
![image](https://user-images.githubusercontent.com/24458276/39410734-43916fb0-4bfd-11e8-9312-cf5c4f24dc5b.png)
 
![image](https://user-images.githubusercontent.com/24458276/39410735-49ea1f1a-4bfd-11e8-8256-2c2b6b2219c2.png)

![image](https://user-images.githubusercontent.com/24458276/39410754-54b7de0a-4bfd-11e8-85e3-daf40a132b6e.png)

![image](https://user-images.githubusercontent.com/24458276/39410756-5eafb23e-4bfd-11e8-88cf-a5ced950e56e.png)

**Comment by Brian-Wuest** [comment]
How did you disable it? Through the configuration options through the Mod Options screen or in the blueprint gui or both?

**Comment by Davoleo** [comment]
in the mod configuration, however they're still there

**Comment by Brian-Wuest** [comment]
Alrighty, they should not even show up on the GUI if you have disabled it in the configuration. 

This is Single Player correct and you have since restarted the game since making that configuration change?

**Comment by Davoleo** [comment]
I have restarted the game. this bug occurs in singleplayer aswell in multiplayer, those screenshots are from multiplayer though

**Comment by Brian-Wuest** [comment]
Cool, thank you for the additional information. I will try to duplicate it.

**Comment by Davoleo** [comment]
no problem!

**Comment by Davoleo** [comment]
Also, I haven't checked, but this might also happen with other blocks which you can block in the config

**Comment by Brian-Wuest** [comment]
The blocks/item which you can enable/disable in the configuration are centered around recipes. Unless you were talking about the Starter House configuration settings.

As a rule I don't disable/enable the actual registration of a block/item just the associated recipes. Though in order for that to work properly, the game has to be restarted due to how the recipe book is registered. (pretty sure on that)

**Comment by Davoleo** [comment]
I mean these ones
![image](https://user-images.githubusercontent.com/24458276/39411818-a7bb84f8-4c11-11e8-9ba5-d4627ce00a4e.png)

However I don't have them disabled, so I don't know if even disabling them they remain in other type of house except the default one 
but I'm sure about the furnace

**Comment by Brian-Wuest** [comment]
Those options have been there for a long time and have worked. When I fixed the issue you reported, I double checked the other settings for the non-basic house to make sure that they would still work and they do.

The furnace issue came up because I recently changed the configuration option which controlled **both** the crafting table and the furnace to having separate options.

If you find any other options which don't appear to be working, feel free to create another issue and I will fix it as fast as I can! :smile:

Closing this issue.
