### ISSUE TITLE
Structure Part Suggestion

### ISSUE THREAD

**Issue by silverfur64** [Brian-Wuest/MC-Prefab#86]
1. Minecraft Version: 1.12.2
    1. Forge Version: 14.23.3.2679
    1. Mod Version: 1.3.0.21

    1. **Enhancement** (Add/Change something)

Details: I have suggestions for the new Structure Part item. I think it is really cool and lets you build more types of structures and might almost be something that could be cool as a starting item in place of the starting house (config option maybe). I think it would be nice though if there were floor/ceiling and roof options. Right now you can kind of make a roof with the stairs but they all look weird.

**Comment by Brian-Wuest** [comment]
Well that was fast!

Thank you for the suggestions! 
I may have to figure something out for some of the materials which don't have a corresponding stairs for the roof.

**Comment by IamAlathe** [comment]
Well, flat roofs are a thing in some places.  Perhaps integrating lighting, like paper lanterns or torches on top if the concern is mob spawns?  If the block has slabs, a lesser angled roof might work.  Would there be an easy way to determine if a player has a mod installed that adds slabs or stairs in that material?  Example:  It may seem weird if they have Repurpose installed, but can't make a roof with grass stairs.

**Comment by Brian-Wuest** [comment]
I like the enthusiasm @IamAlathe, however I am lazy and also want to only allow generally available overworld vanilla materials for this stuff. Otherwise I have to make the recipes way more expensive or offer variant recipes to make the blueprint include nether/end/prismarine materials.

I was able to separate out the Stair materials from the regular blocks. Both Roof style and Stair style (duh!) will use the stair material list which is below.

The Andesite, Diorite and Granite stairs are available due to this mod. :smile:
1. Cobblestone
1. Stone Brick
1. Andesite
1. Diorite
1. Granite
1. Oak
1. Spruce
1. Birch
1. Acacia
1. Dark Oak

**Comment by Brian-Wuest** [comment]
Screenshot of a 2 block high roof.

Even a 1 block high roof would include a capstone.

All capstones are the same block type as the main stair but it's a bottom slab. This way torches are not necessary to avoid monsters spawning on the roof.

![2018-05-30_20 38 55](https://user-images.githubusercontent.com/13502068/40756498-8a4113e8-6449-11e8-9fcc-24391ce7d035.png)

**Comment by IamAlathe** [comment]
Nah, not lazy, I've seen the way you push stuff out. 😁 But you are correct, that would have required a lot of work, and it's arguably outside the scope of what you're doing with this mod.  And yes, it would be silly not to allow stairs and slabs added directly by this mod.  Looks like you're on track! 👍

**Comment by Brian-Wuest** [comment]
This has been included in 1.3.0.22 which is available on CurseForge.

Closing.
