### ISSUE TITLE
Warehouse preview button crash...

### ISSUE THREAD

**Issue by therealericbj** [Brian-Wuest/MC-Prefab#9]
Clicking Preview button to placement of building crashes my single player game.

It gives me this crash report, http://pastebin.com/w45HKQ4W.

Mod version - 1.1.1.0

Forge - 2075

**Comment by Brian-Wuest** [comment]
What building were you trying to preview?

**Comment by Brian-Wuest** [comment]
I was not able to duplicate this on my clean Development system and after doing some research this appears to be an issue coming from ArchitectureCraft.

There was a similar issue reported with ImmersiveEngineering (https://github.com/BluSunrize/ImmersiveEngineering/issues/987).

The line bolded here is from ArchitectureCraft, it's interjecting on the basic rendering my mod is doing.

```
at net.minecraft.client.renderer.BlockRendererDispatcher.func_175016_a(BlockRendererDispatcher.java:124)
at **gcewing.architecture.BaseModClient$CustomBlockRendererDispatcher.func_175016_a(BaseModClient.java:677**)
at com.wuest.prefab.Render.StructureRenderHandler.doRenderComponent(StructureRenderHandler.java:235)
```

Please create an issue with ArchictectureCraft so that this can be addressed since they are breaking this functionality.

I am closing this issue.
