### ISSUE TITLE
Error while building a horse stable 

### ISSUE THREAD

**Issue by Davoleo** [Brian-Wuest/MC-Prefab#90]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.12.2
    1. Forge Version: 2707
    1. Mod Version: 1.3.0.22
1. What type of issue is this?
    1. **Bug** (Something doesn't work the way you expect or the game crashes/has an issue)
This happens while building a horse stable... I was testing in a flat world, and it does work with the advanced horse stable but not with the basic one

Here's what the game says:
![image](https://user-images.githubusercontent.com/24458276/41169102-2bb26e8e-6b48-11e8-9865-9b4947d3b98a.png)
But there isn't any protected blocks in the area
Furthermore it can't be a problem of spawn chunks that are protected because I tried it far away and the issue always shown up

Log: 
[latest.log](https://github.com/Brian-Wuest/MC-Prefab/files/2085171/latest.log)

**Comment by Davoleo** [comment]
Further screenshot, there seems to be a layer of dirt under the building preview, I don't know if it could help investigate through the problem but I'll post it anyway
![image](https://user-images.githubusercontent.com/24458276/41169543-a0f03766-6b49-11e8-8ab7-a03feb52bab9.png)

**Comment by Davoleo** [comment]
I found out I get the same issue testing the fish pond and the warehouse, I wander if it's a problem of mine

**Comment by Brian-Wuest** [comment]
Those buildings have stuff underground for various things. For the horse stable it's for the redstone circuits. For the fishpond it's for all of the water and other things in the pond. The warehouse has a basement.

In this case the protected blocks are the layer of bedrock at the bottom of the superflat world. Since those blocks are indestuctable, that message is shown.

If you want to generate these buildings in a superflat world, you will have to add a few layers (like 8 at least) of dirt or some other destuctable block.

**Comment by Davoleo** [comment]
oki, didn't know that, thanks for the help
[closing the issue]
